Description:
  This template builds EFS for WordPress.

Resources:
  EFS:
    Type: AWS::EFS::FileSystem
  EFSMountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId   : !Ref EFS
      SecurityGroups :
        - !Ref EFSSecurityGroup 
      SubnetId       : !Ref PrivateSubnet1
  EFSMountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId   : !Ref EFS
      SecurityGroups :
        - !Ref EFSSecurityGroup 
      SubnetId       : !Ref PrivateSubnet2

Parameters:
  EFSSecurityGroup:
    Type: String
    Description   : Please enter VPC Security Group ID for EFS.
  PrivateSubnet1:
    Type: String
    Description   : Please enter VPC private subnet1 for MountTarget.
  PrivateSubnet2:
    Type: String
    Description   : Please enter VPC private subnet2 for MountTarget.

Outputs:
  EFS:
    Value: !Ref EFS
