Description:
  This template builds VPC for WordPress.

Parameters:
  WordPressVPCCIDR:
    Type: String
    Default: 10.0.0.0/16
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for VPC.
  WordPressPublicSubnet1CIDR:
    Type: String
    Default: 10.0.0.0/24
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for Public subnet 1.
  WordPressPublicSubnet2CIDR:
    Type: String
    Default: 10.0.1.0/24
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for Public subnet 2.
  WordPressPrivateSubnet1CIDR:
    Type: String
    Default: 10.0.2.0/24
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for Private subnet 1.
  WordPressPrivateSubnet2CIDR:
    Type: String
    Default: 10.0.3.0/24
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for Private subnet 2.

Resources:
  WordPressVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock          : !Ref WordPressVPCCIDR
      EnableDnsHostnames : true
  WordPressInternetGateway:
    Type: AWS::EC2::InternetGateway
  WordPressInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId : !Ref WordPressInternetGateway
      VpcId             : !Ref WordPressVPC
  WordPressPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId               : !Ref WordPressVPC
      AvailabilityZone    : !Select [ 0, !GetAZs "" ]
      CidrBlock           : !Ref WordPressPublicSubnet1CIDR
  WordPressPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId               : !Ref WordPressVPC
      AvailabilityZone    : !Select [ 1, !GetAZs "" ]
      CidrBlock           : !Ref WordPressPublicSubnet2CIDR
  WordPressPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId               : !Ref WordPressVPC
      AvailabilityZone    : !Select [ 0, !GetAZs "" ]
      CidrBlock           : !Ref WordPressPrivateSubnet1CIDR
  WordPressPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId               : !Ref WordPressVPC
      AvailabilityZone    : !Select [ 1, !GetAZs "" ]
      CidrBlock           : !Ref WordPressPrivateSubnet2CIDR
  WordPressElasticIP1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: !Ref WordPressVPC
  WordPressElasticIP2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: !Ref WordPressVPC
  WordPressNatGateway1:
    Type: AWS::EC2::NatGateway
    DependsOn: WordPressInternetGateway
    Properties:
      AllocationId : !GetAtt WordPressElasticIP1.AllocationId
      SubnetId     : !Ref WordPressPublicSubnet1
  WordPressNatGateway2:
    Type: AWS::EC2::NatGateway
    DependsOn: WordPressInternetGateway
    Properties:
      AllocationId : !GetAtt WordPressElasticIP2.AllocationId
      SubnetId     : !Ref WordPressPublicSubnet2
  WordPressPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId : !Ref WordPressVPC
  WordPressPublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId         : !Ref WordPressPublicRouteTable
      DestinationCidrBlock : 0.0.0.0/0
      GatewayId            : !Ref WordPressInternetGateway
  WordPressPrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId : !Ref WordPressVPC
  WordPressPrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId : !Ref WordPressVPC
  WordPressPrivateRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId         : !Ref WordPressPrivateRouteTable1
      DestinationCidrBlock : 0.0.0.0/0
      NatGatewayId         : !Ref WordPressNatGateway1
  WordPressPrivateRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId         : !Ref WordPressPrivateRouteTable2
      DestinationCidrBlock : 0.0.0.0/0
      NatGatewayId         : !Ref WordPressNatGateway2
  WordPressPublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref WordPressPublicSubnet1
      RouteTableId: !Ref WordPressPublicRouteTable
  WordPressPublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref WordPressPublicSubnet2
      RouteTableId: !Ref WordPressPublicRouteTable
  WordPressPrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref WordPressPrivateSubnet1
      RouteTableId: !Ref WordPressPrivateRouteTable1
  WordPressPrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref WordPressPrivateSubnet2
      RouteTableId: !Ref WordPressPrivateRouteTable2

Outputs:
  WordPressVPC:
    Value: !Ref WordPressVPC
  WordPressPublicSubnet1:
    Value: !Ref WordPressPublicSubnet1
  WordPressPublicSubnet2:
    Value: !Ref WordPressPublicSubnet2
  WordPressPrivateSubnet1:
    Value: !Ref WordPressPrivateSubnet1
  WordPressPrivateSubnet2:
    Value: !Ref WordPressPrivateSubnet2
