Description:
  This template builds RDS for WordPress.

Parameters:
  WordPressPrivateSubnet1:
    Type: String
    Description   : Please enter VPC private subnet1 for SubnetGroup.
  WordPressPrivateSubnet2:
    Type: String
    Description   : Please enter VPC private subnet2 for SubnetGroup.
  WordPressRDSInstanceClass:
    Type          : String
    Default       : db.t2.small
    AllowedValues :
      - db.t2.micro
      - db.t2.small
      - db.t2.medium
      - db.t2.large
      - db.t2.xlarge
      - db.t2.2xlarge
      - db.m5.large
      - db.m5.xlarge
      - db.m5.2xlarge
      - db.m5.4xlarge
      - db.m5.12xlarge
      - db.m5.24xlarge
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
      - db.r4.16xlarge
    Description   : Select RDS instance class.
  WordPressRDSDBName:
    Type           : String
    Default        : wordpress
    MinLength      : 1
    MaxLength      : 16
    AllowedPattern : '[a-z]+'
  WordPressRDSMasterUser:
    Type           : String
    Default        : admin
    MinLength      : 1
    MaxLength      : 16
    NoEcho         : true
    AllowedPattern : '[a-z]+'
  WordPressRDSMasterPassword :
    Type           : String
    Default        : password
    MinLength      : 8
    MaxLength      : 16
    NoEcho         : true
    AllowedPattern : '[^\/@"]+'
  WordPressDBSecurityGroup:
    Type: String
    Description   : Please enter VPC Security Group ID for RDS.

Resources:
  WordPressRDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "SubnetGroup for WordPress"
      SubnetIds:
        - !Ref WordPressPrivateSubnet1
        - !Ref WordPressPrivateSubnet2
  WordPressRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage   : 20
      DBSubnetGroupName  : !Ref WordPressRDSSubnetGroup
      DBInstanceClass    : !Ref WordPressRDSInstanceClass
      DBName             : !Ref WordPressRDSDBName
      MasterUsername     : !Ref WordPressRDSMasterUser
      MasterUserPassword : !Ref WordPressRDSMasterPassword
      Engine             : MySQL
      MultiAZ            : true
      PubliclyAccessible : false
      StorageType        : gp2
      VPCSecurityGroups  :
        - !Ref WordPressDBSecurityGroup
    DeletionPolicy: Delete

Outputs:
  WordPressRDSEndpoint:
    Value: !GetAtt WordPressRDSInstance.Endpoint.Address
