Description:
  This template builds RDS for WordPress.

Resources:
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "SubnetGroup for WordPress"
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage   : 20
      DBSubnetGroupName  : !Ref RDSSubnetGroup
      DBInstanceClass    : !Ref RDSInstanceClass
      DBName             : !Ref RDSDBName
      MasterUsername     : !Ref RDSMasterUser
      MasterUserPassword : !Ref RDSMasterPassword
      Engine             : MySQL
      MonitoringInterval : 0
      MultiAZ            : true
      Port               : 3306
      PubliclyAccessible : false
      StorageType        : gp2
      VPCSecurityGroups  :
        - !Ref DBSecurityGroup

Parameters:
  PrivateSubnet1:
    Type: String
  PrivateSubnet2:
    Type: String
  RDSInstanceClass:
    Type: String
  RDSDBName:
    Type: String
  RDSMasterUser:
    Type: String
  RDSMasterPassword:
    Type: String
  DBSecurityGroup:
    Type: String

Outputs:
  RDSEndpoint:
    Value:
      Fn::GetAtt:
        - RDSInstance
        - Endpoint.Address
