Description:
  This template builds seciruty configuration for WordPress.
Resources:
  ELBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId                : !Ref VPC
      GroupDescription     : SecurityGroup for ELB.
      SecurityGroupIngress :
      - IpProtocol            : tcp
        FromPort              : '80'
        ToPort                : '80'
        CidrIp                : 0.0.0.0/0
      - IpProtocol            : tcp
        FromPort              : '443'
        ToPort                : '443'
        CidrIp                : 0.0.0.0/0
  APSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId                : !Ref VPC
      GroupDescription     : SecurityGroup for WordPress Servers.
      SecurityGroupIngress :
      - IpProtocol            : tcp
        FromPort              : '80'
        ToPort                : '80'
        SourceSecurityGroupId : !Ref ELBSecurityGroup
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId                : !Ref VPC
      GroupDescription     : SecurityGroup for MySQL Servers.
      SecurityGroupIngress :
      - IpProtocol            : tcp
        FromPort              : '3306'
        ToPort                : '3306'
        SourceSecurityGroupId : !Ref APSecurityGroup
Parameters:
  VPC:
    Type: "String"
Outputs:
  ELBSecurityGroup:
    Value: !Ref ELBSecurityGroup
  APSecurityGroup:
    Value: !Ref APSecurityGroup
  DBSecurityGroup:
    Value: !Ref DBSecurityGroup
