Description:
  This template buils seciruty configuration for WordPress.
Resources:
  ELBSecurityGroup: # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription     : SecurityGroup for ELB.
      SecurityGroupIngress :
      - IpProtocol            : tcp
        FromPort              : '80'
        ToPort                : '80'
        CidrIp                : 0.0.0.0/0
      - IpProtocol            : tcp
        FromPort              : '443'
        ToPort                : '443'
        CidrIp                : 0.0.0.0/0
      VpcId                : !ImportValue WordPressVPC
  APSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription     : SecurityGroup for WordPress Servers.
      SecurityGroupIngress :
      - IpProtocol            : tcp
        FromPort              : '80'
        ToPort                : '80'
        SourceSecurityGroupId : !Ref ELBSecurityGroup
      VpcId                : !ImportValue WordPressVPC
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription     : SecurityGroup for MySQL Servers.
      SecurityGroupIngress :
      - IpProtocol            : tcp
        FromPort              : '3306'
        ToPort                : '3306'
        SourceSecurityGroupId : !Ref APSecurityGroup
      VpcId                : !ImportValue WordPressVPC
Outputs:
  ELBSecurityGroup:
    Value: !Ref ELBSecurityGroup
    Export:
      Name: ELBSecurityGroup
  APSecurityGroup:
    Value: !Ref APSecurityGroup
    Export:
      Name: APSecurityGroup
  DBSecurityGroup:
    Value: !Ref DBSecurityGroup
    Export:
      Name: DBSecurityGroup
