Description:
  This template wraps WordPress templates.
Resources:
  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL : https://s3-ap-northeast-1.amazonaws.com/dozono-cloudformation/WordPress/Network-2az.yml
      Parameters  :
        VPCCIDR            : !Ref VPCCIDR
        PublicSubnet1CIDR  : !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR  : !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR : !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR : !Ref PrivateSubnet2CIDR
  Security:
    Type: AWS::CloudFormation::Stack
    Properties :
      TemplateURL : https://s3-ap-northeast-1.amazonaws.com/dozono-cloudformation/WordPress/Security.yml
      Parameters  :
        WordPressVPC: !GetAtt Network.Outputs.WordPressVPC
  RDS:
    Type: AWS::CloudFormation::Stack
    Properties :
      TemplateURL : https://s3-ap-northeast-1.amazonaws.com/dozono-cloudformation/WordPress/RDS.yml
      Parameters  :
        RDSInstanceClass  : !Ref RDSInstanceClass
        RDSMasterUser     : !Ref RDSMasterUser
        RDSMasterPassword : !Ref RDSMasterPassword
        DBSecurityGroup   : !GetAtt Security.Outputs.DBSecurityGroup
        PrivateSubnet1    : !GetAtt Network.Outputs.WordPressPrivateSubnet1
        PrivateSubnet2    : !GetAtt Network.Outputs.WordPressPrivateSubnet2
  AP:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL : https://s3-ap-northeast-1.amazonaws.com/dozono-cloudformation/WordPress/AP.yml
      Parameters  :
        KeyName           : !Ref KeyName
        ELBSecurityGroup  : !GetAtt Security.Outputs.ELBSecurityGroup
        APSecurityGroup   : !GetAtt Security.Outputs.APSecurityGroup
        PublicSubnet1     : !GetAtt Network.Outputs.WordPressPublicSubnet1
        PublicSubnet2     : !GetAtt Network.Outputs.WordPressPublicSubnet2
        PrivateSubnet1    : !GetAtt Network.Outputs.WordPressPrivateSubnet1
        PrivateSubnet2    : !GetAtt Network.Outputs.WordPressPrivateSubnet2
        RDSDBName         : !Ref RDSDBName
        RDSMasterUser     : !Ref RDSMasterUser
        RDSMasterPassword : !Ref RDSMasterPassword
        RDSEndpoint       : !GetAtt RDS.Outputs.RDSEndpoint
Parameters:
  RDSInstanceClass:
    Type          : String
    Default       : db.t2.small
    AllowedValues :
      - db.t2.micro
      - db.t2.small
      - db.t2.medium
      - db.t2.large
      - db.t2.xlarge
      - db.t2.2xlarge
    Description   : Select RDS instance class.
  RDSDBName:
    Type           : String
    Default        : wordpress
    MinLength      : 1
    MaxLength      : 16
    NoEcho         : true
    AllowedPattern : '[a-z]+'
  RDSMasterUser:
    Type           : String
    Default        : admin
    MinLength      : 1
    MaxLength      : 16
    NoEcho         : true
    AllowedPattern : '[a-z]+'
  RDSMasterPassword :
    Type           : String
    Default        : password
    MinLength      : 8
    MaxLength      : 16
    NoEcho         : true
    AllowedPattern : '[^\/@"]+'
  VPCCIDR:
    Type: String
    Default: 10.0.0.0/16
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for VPC.
  PublicSubnet1CIDR:
    Type: String
    Default: 10.0.0.0/24
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for Public subnet 1.
  PublicSubnet2CIDR:
    Type: String
    Default: 10.0.1.0/24
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for Public subnet 2.
  PrivateSubnet1CIDR:
    Type: String
    Default: 10.0.2.0/24
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for Private subnet 1.
  PrivateSubnet2CIDR:
    Type: String
    Default: 10.0.3.0/24
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for Private subnet 2.
  KeyName:
    Description : The EC2 Key Pair to allow SSH access to the instance.
    Type        : 'AWS::EC2::KeyPair::KeyName'
Outputs:
  WordPressURL:
    Value: !GetAtt AP.Outputs.ELBURL
