Description:
  This template wraps WordPress templates.

Resources:
  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL : https://s3-ap-northeast-1.amazonaws.com/dozono-cloudformation/WordPress/Network.yml
      Parameters  :
        VPCCIDR            : !Ref VPCCIDR
        PublicSubnet1CIDR  : !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR  : !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR : !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR : !Ref PrivateSubnet2CIDR
  Security:
    Type: AWS::CloudFormation::Stack
    Properties :
      TemplateURL : https://s3-ap-northeast-1.amazonaws.com/dozono-cloudformation/WordPress/Security.yml
      Parameters  :
        VPC: !GetAtt Network.Outputs.VPC
  EFS:
    Type: AWS::CloudFormation::Stack
    Properties :
      TemplateURL : https://s3-ap-northeast-1.amazonaws.com/dozono-cloudformation/WordPress/EFS.yml
      Parameters  :
        EFSSecurityGroup: !GetAtt Security.Outputs.EFSSecurityGroup
        PrivateSubnet1    : !GetAtt Network.Outputs.PrivateSubnet1
        PrivateSubnet2    : !GetAtt Network.Outputs.PrivateSubnet2
  RDS:
    Type: AWS::CloudFormation::Stack
    Properties :
      TemplateURL : https://s3-ap-northeast-1.amazonaws.com/dozono-cloudformation/WordPress/RDS.yml
      Parameters  :
        PrivateSubnet1    : !GetAtt Network.Outputs.PrivateSubnet1
        PrivateSubnet2    : !GetAtt Network.Outputs.PrivateSubnet2
        RDSInstanceClass  : !Ref RDSInstanceClass
        RDSDBName         : !Ref RDSDBName
        RDSMasterUser     : !Ref RDSMasterUser
        RDSMasterPassword : !Ref RDSMasterPassword
        DBSecurityGroup   : !GetAtt Security.Outputs.DBSecurityGroup
  ASG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL : https://s3-ap-northeast-1.amazonaws.com/dozono-cloudformation/WordPress/ASG.yml
      Parameters  :
        PublicSubnet1     : !GetAtt Network.Outputs.PublicSubnet1
        PublicSubnet2     : !GetAtt Network.Outputs.PublicSubnet2
        PrivateSubnet1    : !GetAtt Network.Outputs.PrivateSubnet1
        PrivateSubnet2    : !GetAtt Network.Outputs.PrivateSubnet2
        ELBSecurityGroup  : !GetAtt Security.Outputs.ELBSecurityGroup
        APSecurityGroup   : !GetAtt Security.Outputs.APSecurityGroup
        EFS               : !GetAtt EFS.Outputs.EFS
        RDSEndpoint       : !GetAtt RDS.Outputs.RDSEndpoint
        RDSDBName         : !Ref RDSDBName
        RDSMasterUser     : !Ref RDSMasterUser
        RDSMasterPassword : !Ref RDSMasterPassword
        EC2InstanceType   : !Ref EC2InstanceType
        KeyName           : !Ref KeyName

Parameters:
  VPCCIDR:
    Type: String
    Default: 10.0.0.0/16
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for VPC.
  PublicSubnet1CIDR:
    Type: String
    Default: 10.0.0.0/24
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for Public subnet 1.
  PublicSubnet2CIDR:
    Type: String
    Default: 10.0.1.0/24
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for Public subnet 2.
  PrivateSubnet1CIDR:
    Type: String
    Default: 10.0.2.0/24
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for Private subnet 1.
  PrivateSubnet2CIDR:
    Type: String
    Default: 10.0.3.0/24
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for Private subnet 2.
  RDSInstanceClass:
    Type          : String
    Default       : db.t2.small
    AllowedValues :
      - db.t2.micro
      - db.t2.small
      - db.t2.medium
      - db.t2.large
      - db.t2.xlarge
      - db.t2.2xlarge
      - db.m5.large
      - db.m5.xlarge
      - db.m5.2xlarge
      - db.m5.4xlarge
      - db.m5.12xlarge
      - db.m5.24xlarge
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
      - db.r4.16xlarge
    Description   : Select RDS instance class.
  RDSDBName:
    Type           : String
    Default        : wordpress
    MinLength      : 1
    MaxLength      : 16
    NoEcho         : true
    AllowedPattern : '[a-z]+'
  RDSMasterUser:
    Type           : String
    Default        : admin
    MinLength      : 1
    MaxLength      : 16
    NoEcho         : true
    AllowedPattern : '[a-z]+'
  RDSMasterPassword :
    Type           : String
    Default        : password
    MinLength      : 8
    MaxLength      : 16
    NoEcho         : true
    AllowedPattern : '[^\/@"]+'
  EC2InstanceType:
    Type          : String
    Default       : t2.micro
    AllowedValues :
      - t2.micro
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.12xlarge
      - m5.24xlarge
    Description   : Select RDS instance class.
  KeyName:
    Description : The EC2 Key Pair to allow SSH access to the instance.
    Type        : 'AWS::EC2::KeyPair::KeyName'

Outputs:
  WordPressURL:
    Value: !GetAtt ASG.Outputs.ELBURL
