Description:
  This template wraps WordPress templates.

Parameters:
  WordPressVPCCIDR:
    Type: String
    Default: 10.0.0.0/16
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for VPC.
  WordPressPublicSubnet1CIDR:
    Type: String
    Default: 10.0.0.0/24
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for Public subnet 1.
  WordPressPublicSubnet2CIDR:
    Type: String
    Default: 10.0.1.0/24
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for Public subnet 2.
  WordPressPrivateSubnet1CIDR:
    Type: String
    Default: 10.0.2.0/24
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for Private subnet 1.
  WordPressPrivateSubnet2CIDR:
    Type: String
    Default: 10.0.3.0/24
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for Private subnet 2.
  WordPressRDSInstanceClass:
    Type          : String
    Default       : db.t2.small
    AllowedValues :
      - db.t2.micro
      - db.t2.small
      - db.t2.medium
      - db.t2.large
      - db.t2.xlarge
      - db.t2.2xlarge
      - db.m5.large
      - db.m5.xlarge
      - db.m5.2xlarge
      - db.m5.4xlarge
      - db.m5.12xlarge
      - db.m5.24xlarge
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
      - db.r4.16xlarge
    Description   : Select RDS instance class.
  WordPressRDSDBName:
    Type           : String
    Default        : wordpress
    MinLength      : 1
    MaxLength      : 16
    AllowedPattern : '[a-z]+'
  WordPressRDSMasterUser:
    Type           : String
    Default        : admin
    MinLength      : 1
    MaxLength      : 16
    NoEcho         : true
    AllowedPattern : '[a-z]+'
  WordPressRDSMasterPassword :
    Type           : String
    Default        : password
    MinLength      : 8
    MaxLength      : 16
    NoEcho         : true
    AllowedPattern : '[^\/@"]+'
  WordPressEC2InstanceType:
    Type          : String
    Default       : t2.micro
    AllowedValues :
      - t2.micro
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.12xlarge
      - m5.24xlarge
    Description   : Select EC2 instance class.
  WordPressKeyName:
    Description : The EC2 Key Pair to allow SSH access to the instance.
    Type        : 'AWS::EC2::KeyPair::KeyName'

Resources:
  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL : https://s3-ap-northeast-1.amazonaws.com/dozono-cloudformation/WordPress/Network.yml
      Parameters  :
        WordPressVPCCIDR            : !Ref WordPressVPCCIDR
        WordPressPublicSubnet1CIDR  : !Ref WordPressPublicSubnet1CIDR
        WordPressPublicSubnet2CIDR  : !Ref WordPressPublicSubnet2CIDR
        WordPressPrivateSubnet1CIDR : !Ref WordPressPrivateSubnet1CIDR
        WordPressPrivateSubnet2CIDR : !Ref WordPressPrivateSubnet2CIDR
  Security:
    Type: AWS::CloudFormation::Stack
    Properties :
      TemplateURL : https://s3-ap-northeast-1.amazonaws.com/dozono-cloudformation/WordPress/Security.yml
      Parameters  :
        WordPressVPC: !GetAtt Network.Outputs.WordPressVPC
  EFS:
    Type: AWS::CloudFormation::Stack
    Properties :
      TemplateURL : https://s3-ap-northeast-1.amazonaws.com/dozono-cloudformation/WordPress/EFS.yml
      Parameters  :
        WordPressEFSSecurityGroup  : !GetAtt Security.Outputs.WordPressEFSSecurityGroup
        WordPressPrivateSubnet1    : !GetAtt Network.Outputs.WordPressPrivateSubnet1
        WordPressPrivateSubnet2    : !GetAtt Network.Outputs.WordPressPrivateSubnet2
  RDS:
    Type: AWS::CloudFormation::Stack
    Properties :
      TemplateURL : https://s3-ap-northeast-1.amazonaws.com/dozono-cloudformation/WordPress/RDS.yml
      Parameters  :
        WordPressPrivateSubnet1    : !GetAtt Network.Outputs.WordPressPrivateSubnet1
        WordPressPrivateSubnet2    : !GetAtt Network.Outputs.WordPressPrivateSubnet2
        WordPressRDSInstanceClass  : !Ref WordPressRDSInstanceClass
        WordPressRDSDBName         : !Ref WordPressRDSDBName
        WordPressRDSMasterUser     : !Ref WordPressRDSMasterUser
        WordPressRDSMasterPassword : !Ref WordPressRDSMasterPassword
        WordPressDBSecurityGroup   : !GetAtt Security.Outputs.WordPressDBSecurityGroup
  ASG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL : https://s3-ap-northeast-1.amazonaws.com/dozono-cloudformation/WordPress/ASG.yml
      Parameters  :
        WordPressPublicSubnet1     : !GetAtt Network.Outputs.WordPressPublicSubnet1
        WordPressPublicSubnet2     : !GetAtt Network.Outputs.WordPressPublicSubnet2
        WordPressPrivateSubnet1    : !GetAtt Network.Outputs.WordPressPrivateSubnet1
        WordPressPrivateSubnet2    : !GetAtt Network.Outputs.WordPressPrivateSubnet2
        WordPressELBSecurityGroup  : !GetAtt Security.Outputs.WordPressELBSecurityGroup
        WordPressAPSecurityGroup   : !GetAtt Security.Outputs.WordPressAPSecurityGroup
        WordPressEFS               : !GetAtt EFS.Outputs.WordPressEFS
        WordPressRDSEndpoint       : !GetAtt RDS.Outputs.WordPressRDSEndpoint
        WordPressRDSDBName         : !Ref WordPressRDSDBName
        WordPressRDSMasterUser     : !Ref WordPressRDSMasterUser
        WordPressRDSMasterPassword : !Ref WordPressRDSMasterPassword
        WordPressEC2InstanceType   : !Ref WordPressEC2InstanceType
        WordPressKeyName           : !Ref WordPressKeyName

Outputs:
  WordPressURL:
    Value: !GetAtt ASG.Outputs.WordPressELBURL
